n1 = float(input("Digite o primeiro número: "))
n2 = float(input("Digite o segundo número: "))
print(f"Soma: {n1 + n2}")
print(f"Subtração: {n1 - n2}")
print(f"Multiplicação: {n1 * n2}")
print(f"Divisão: {n1 / n2 if n2 != 0 else 'Erro: divisão por zero'}")